[package]
name = "lbrp"
version = "0.1.0"
edition = "2021"

[dependencies]
cc-server-kit = { git = "https://github.com/markcda/cc-server-kit.git", default-features = false, features = ["oapi", "http3", "utils", "proxy", "reqwest-msgpack", "reqwest-http3", "log-without-filtering"] }
futures-util = { version = "0.3", default-features = false }
notify = "6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
