[package]
name = "lbrp"
version = "0.1.1"
edition = "2024"

[dependencies]
cc-server-kit = { git = "https://github.com/impulse-sw/cc-services.git", tag = "0.6.3-2", default-features = false, features = ["cors", "oapi", "http3", "cc-utils", "proxy", "force-https", "reqwest-msgpack", "reqwest-http3", "log-without-filtering"] }
c3a-worker = { git = "ssh://git@github.com/impulse-sw/c3a.git", tag = "wip38", optional = true }
futures-util = { version = "0.3", default-features = false }
notify = "6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = ["c3a"]
c3a = ["dep:c3a-worker"]
