project_name: lbrp
version: 4
langs:
  - rust
targets:
  - arch: x86_64
    os: linux
    os_derivative: any
    os_version:
      type: no
cache_files:
  - .git
  - Cargo.lock
  - target
artifacts:
  - target/release/lbrp
  - lbrp-keyring.json
variables:
  - title: lbrp-adm-pass
    is_secret: true
    value:
      type: from_env_file
      env_file_path: .env
      key: LBRP_C3A_ADMP
  - title: lbrp-adm-kp
    is_secret: true
    value:
      type: from_env_file
      env_file_path: .env
      key: LBRP_C3A_ADMCDPUB
place_artifacts_into_project_root:
  - from: target/release/lbrp
    to: lbrp
  - from: lbrp-keyring.json
    to: ../lbrp-keyring.json
pipelines:
  - title: lint
    desc: Got from `LBRP Pipeline`.
    info: lbrp@0.1.0
    tags:
      - cargo
      - upx
      - reqwest
    default: false
    exclusive_exec_tag: lints
    actions:
      - title: Lint without features
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: RUSTFLAGS='--cfg reqwest_unstable' cargo clippy --no-default-features
              show_success_output: true
      - title: Lint with all features
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: RUSTFLAGS='--cfg reqwest_unstable' cargo clippy
              show_success_output: true
  - title: build
    desc: Got from `LBRP Pipeline`.
    info: lbrp@0.1.0
    tags:
      - cargo
      - upx
      - reqwest
    default: true
    actions:
      - title: Lint
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: RUSTFLAGS='--cfg reqwest_unstable' cargo clippy
              show_success_output: true
      - title: Format
        info: cargo-fmt@0.1.0
        tags:
          - rust
          - cargo
          - fmt
        exec_in_project_dir: true
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo fmt -- --config tab_spaces=2,max_width=120 */**/*.rs
      - title: Build
        info: cargo-rel@0.1.0
        tags:
          - rust
          - cargo
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: RUSTFLAGS='--cfg reqwest_unstable' cargo build --release
      - title: Compress
        info: upx-compress@0.1.0
        tags:
          - upx
        action:
          type: post_build
          supported_langs:
            - any
          commands:
            - bash_c: upx <af>
              placeholders:
                - <af>
              replacements:
                - group:
                    - from: <af>
                      to:
                        title: target/release/lbrp
                        is_secret: false
                        value:
                          type: plain
                          value: target/release/lbrp
  - title: deploy
    desc: Got from `LBRP Pipeline`.
    info: lbrp@0.1.0
    tags:
      - cargo
      - upx
      - reqwest
    default: false
    actions:
      - title: Lint
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: RUSTFLAGS='--cfg reqwest_unstable' cargo clippy
      - title: Format
        info: cargo-fmt@0.1.0
        tags:
          - rust
          - cargo
          - fmt
        exec_in_project_dir: true
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo fmt -- --config tab_spaces=2,max_width=120 */**/*.rs
      - title: Build
        info: cargo-rel@0.1.0
        tags:
          - rust
          - cargo
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: RUSTFLAGS='--cfg reqwest_unstable' cargo build --release
      - title: Compress
        info: upx-compress@0.1.0
        tags:
          - upx
        action:
          type: post_build
          supported_langs:
            - any
          commands:
            - bash_c: upx <af>
              placeholders:
                - <af>
              replacements:
                - group:
                    - from: <af>
                      to:
                        title: target/release/lbrp
                        is_secret: false
                        value:
                          type: plain
                          value: target/release/lbrp
      - title: Run
        info: run-lbrp@0.1.0
        tags:
          - lbrp
        exec_in_project_dir: false
        action:
          type: observe
          command:
            bash_c: sudo LBRP_C3A_ADMP='$1' LBRP_C3A_ADMCDPUB='$2' ./target/release/lbrp
            ignore_fails: true
            show_success_output: true
            show_bash_c: false
            placeholders:
              - $1
              - $2
            replacements:
              - group:
                  - from: $1
                    to:
                      title: lbrp-adm-pass
                      is_secret: true
                      value:
                        type: from_env_file
                        env_file_path: .env
                        key: LBRP_C3A_ADMP
                  - from: $2
                    to:
                      title: lbrp-adm-kp
                      is_secret: true
                      value:
                        type: from_env_file
                        env_file_path: .env
                        key: LBRP_C3A_ADMCDPUB
