[package]
name = "lbrp-types"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
authnz-common = { workspace = true, features = ["app-client-types"] }
serde = { workspace = true }
